### ISSUE TITLE
Sunlamp and hydroponics basin compatibility? 

### ISSUE THREAD

**Issue by Jellypowered** [EbonJaeger/RePowerReborn#2]
Hello! Thank you for continuing this mod, I have tried to enable repower for two in game items, and am not getting the expected results. I haven't dug through the game code to even see if this is possible, perhaps you have some ideas? 

I have a Efficent utilities so the sunlamp when active costs 500w in my game. I attempted to mirror that with the following defs. 

	<RePower.RePowerDef>
		
		<defName>RePowerHydroponicsBasin</defName>
		<targetDef>HydroponicsBasin</targetDef>
		<lowPower>-10</lowPower>
		<highPower>-75</highPower>
		<poweredWorkbench>false</poweredWorkbench>
		<poweredReservable>true</poweredReservable>
	</RePower.RePowerDef>
	
	<RePower.RePowerDef>
		
		<defName>RePowerSunLamp</defName>
		<targetDef>SunLamp</targetDef>
		<lowPower>-10</lowPower>
		<highPower>-500</highPower>
		<poweredWorkbench>false</poweredWorkbench>
		<poweredReservable>true</poweredReservable>
	</RePower.RePowerDef>

However, regardless of the time of day, the above additions to the RePowerVanillaBuildings.xml only work to limit the power consumption to 10w. When the sunlamp turns on, it does not increase the consumption to 500w as intended.  

Open for suggestions, I tried setting both of them to 
```
	<poweredWorkbench>true</poweredWorkbench>
	<poweredReservable>false</poweredReservable>
```

but same results. 

Perhaps adding a check for "scheduled on/off"
As the core sunlamp def has this little bit in it, 
```
  <li Class="CompProperties_Schedule">
        <!-- Match plant growing times -->
        <startTime>0.25</startTime>
        <endTime>0.8</endTime>
        <offMessage>Off for plant resting period</offMessage>
      </li>
```
Maybe adding an option such as:
```
	<poweredWorkbench>false</poweredWorkbench>
	<poweredReservable>false</poweredReservable>
        <poweredScheduled>true</poweredScheduled>  <!-- Only used for powered items with a schedule!-->
```
Thanks for your thoughts!

**Comment by Jellypowered** [comment]
As an afterthought... It seems there is no schedule for hydroponics basins, I suppose I can live with the basins "being on" all the time, in some forms of hydroponics there is a constant need for nutrients to be pumped so that's realistic haha, and the core def for it doesn't seem to have any kind of schedule settings, it's dependent on light levels. 

But idle power usage for items with scheduled on/off would be a great addition to this mod!

**Comment by EbonJaeger** [comment]
Agreed, that would be good to have for things like sunlamps.

As for the hydroponics basin, it would be nice to only have it on max power when there is something planted in it. I wonder if there is a way to check that...

**Comment by Jellypowered** [comment]
I've decompiled the Building_PlantGrower from the source code, here's what is included in the core. 

Looks like we could check with some kind of "PlantsOnMe" check. 
```
// RimWorld.Building_PlantGrower
// Snip
	public IEnumerable<Plant> PlantsOnMe
	{
		get
		{
			if (!base.Spawned)
			{
				yield break;
			}
			CellRect.CellRectIterator cri = this.OccupiedRect().GetIterator();
			while (!cri.Done())
			{
				List<Thing> thingList = base.Map.thingGrid.ThingsListAt(cri.Current);
				for (int i = 0; i < thingList.Count; i++)
				{
					Plant p = thingList[i] as Plant;
					if (p != null)
					{
						yield return p;
					}
				}
				cri.MoveNext();
			}
		}
	}
//Snip
```

**Comment by EbonJaeger** [comment]
Great find! I think I might have it for the HydroponicsBasins, lemme just do some quick testing.

**Comment by EbonJaeger** [comment]
Added hydroponics basin handling. Heres the def i used for testing:
```xml
  <RePower.RePowerDef>
    <!-- HydroponicsBasins -->
    <defName>RePowerHydroponicsBasin</defName>
    <targetDef>HydroponicsBasin</targetDef>
    <lowPower>-5</lowPower>
    <highPower>-75</highPower>
    <poweredWorkbench>false</poweredWorkbench>
    <poweredReservable>false</poweredReservable>
  </RePower.RePowerDef>
```

**Comment by Jellypowered** [comment]
Great I'll check it out later, I don't have the ability/time to compile your source at the moment to test :) I'll let you know!

**Comment by EbonJaeger** [comment]
I'll attach a zip for the entire mod to save you having to compile it. :D
[RePowerReborn.zip](https://github.com/EbonJaeger/RePowerReborn/files/3617459/RePowerReborn.zip)

**Comment by Jellypowered** [comment]
Quick testing shows it works as intended now using your supplied folder! 

Thank you so much! 
Do you accept donations?

**Comment by Jellypowered** [comment]
So for the sunlamps, I don't have VS and don't make mods, but maybe this will be a good starting place? 

In Repower.cs
add
Tracker.EvalSunLamp();


In Tracker.cs
add 

```c#
public HashSet<Building> SunLamp = new HashSet<Building>();

private ThingDef SunLamp;

SunLampDef = ThingDef.Named("SunLamp");

    public void EvalSunLamp()
    {
        foreach (var sunlamps in SunLamp)
        {
            if (sunlamps == null) continue;
            if (sunlamps.Map == null) continue;
					
            var ScheduledOn = sunlamps.CompSchedule // (Dunno what i'm doin here Fill in the rest? lol)
					
            if (!ScheduledOn) continue;
            BuildingsInUse.Add(sunlamps)
        }
    }
```

**Comment by EbonJaeger** [comment]
Good find again on CompSchedule! I think it would be even better to add a field to the def to signify that an item is on a schedule to keep it more generic. I'm just not sure what that does with pre-existing defs without the field defined... Gonna have to test that.

**Comment by Jellypowered** [comment]
Take a peek at my fork, I have the basic idea down, just need someone who knows code better than I to make it fluid. 

It works on One sunlamp. But never "clears" for low power mode. The second sunlamp never goes "full power" which leads me to believe I'm not scanning properly for all the sunlamps. 

I've been messing with it over the last few days, hope this helps give you an idea of where to proceed. :)

**Comment by EbonJaeger** [comment]
Sorry, already found the solution I wanted before even seeing your comment. xD

**Comment by Jellypowered** [comment]
No worries! I’ve enjoyed tinkering with it trying to learn lol

**Comment by EbonJaeger** [comment]
Note that for scheduled buildings, you'll need the new field in your def:
```xml
<scheduledPower>true</scheduledPower>
```
